services:
  - type: web
    name: craveaway-server
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build  # make sure "build" compiles TypeScript
    startCommand: node dist/server.js           # path to compiled JS version of server.ts
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: craveaway-db
          property: connectionString

databases:
  - name: craveaway-db
    plan: free
  
